---
- name: configure the bgp routing process for ios device
  ios_bgp:
    bgp_as: "{{ bgp.config.bgp_as | default(omit) }}"
    router_id: "{{ bgp.config.router_id | default(omit) }}"
    log_neighbor_changes: "{{ bgp.config.log_neighbor_changes | default(omit) }}"
    redistribute: "{{ bgp.config.redistribute | default(omit) }}"
    networks: "{{ bgp.config.networks | default(omit) }}"
    neighbors: "{{ bgp.config.neighbors | default(omit) }}"
    address_family: "{{ bgp.config.address_family | default(omit) }}"
    state: "{{ bgp.config.state | default(omit) }}"
  when: bgp.config is defined
