---
- name: configure vrf definitions
  ios_vrf_definition:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    route_distinguisher: "{{ item.route_distinguisher | default(omit) }}"
    route_target: "{{ item.route_target | default(omit) }}"
    address_family: "{{ item.address_family | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ vrf_definitions }}"
  when: vrf_definitions is defined

- name: purge stale configuration from device
  block:
    - name: get current vrf definitions
      cli:
        command: show ip vrf detail
      register: current_vrf_definitions

    - name: filter show command output
      set_fact:
        current_vrf_definitions: "{{ current_vrf_definitions.stdout | show_command('show_ip_vrf_detail') }}"

    - name: remove vrf definitions
      ios_vrf_definition:
        name: "{{ item.name }}"
        state: absent
      with_items: "{{ current_vrf_definitions }}"
      when: item.name not in vrf_definitions | map(attribute='name') | list
  when: ios_vrf_definitions_purge
