---

- name: Push VPN configuration to CSR device
  ios_config:
    src: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - configure_vpn.j2
      paths:
        - "templates/cloud_vpn/providers/csr/initiator/{{ cloud_vpn_responder_provider }}"
        - templates/cloud_vpn/providers/csr/initiator
  delegate_to: initiator
