---

- name: Push routing configuration to CSR device
  ios_config:
    src: "cloud_vpn/providers/csr/initiator/{{ cloud_vpn_responder_provider }}/configure_routing_{{ cloud_vpn_routing }}.j2"
  delegate_to: initiator
